name: py-gcp -> DockerHub

on: 
  workflow_dispatch:
    inputs:
      # BASE_IMAGE is the full user/name:tag of the base FaaSr image (stored in DockerHub) to build from 
      BASE_IMAGE:
        description: 'user/name:tag of the base FaaSr image e.g. janedoe/base-python:0.1.0'
        required: true
        default: 'nolcut/faasr-rpc-test:0.1.6'
      # TARGET_NAME is the name of the FaaS-specific image to build
      # Examples: gcp-python
      TARGET_NAME:
        description: 'name of the FaaS-specific image to build'
        required: true
        default: 'gcp-python'
      # FAASR_VERSION is the FaaSr-py version tag to be used for this base FaaSr image
      FAASR_VERSION:
        description: 'FaaSr-py version'
        required: true 
      # FAASR_INSTALL_REPO is the GitHub repo to install FaaSr from
      FAASR_INSTALL_REPO:
        description: 'GitHub repo to install FaaSr-py from'
        required: true
        default: 'FaaSr/FaaSr-Backend'

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build GCP Container image
        run: |
          cd faas_specific
          docker build -f gcp.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.TARGET_NAME }}:${{ github.event.inputs.FAASR_VERSION }} --build-arg BASE_IMAGE=${{ github.event.inputs.BASE_IMAGE }} --build-arg FAASR_VERSION=${{ github.event.inputs.FAASR_VERSION }} --build-arg FAASR_INSTALL_REPO=${{ github.event.inputs.FAASR_INSTALL_REPO }} .
      
      - name: Push GCP image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.TARGET_NAME }}:${{ github.event.inputs.FAASR_VERSION }}
      
      - name: Tag and push as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.TARGET_NAME }}:${{ github.event.inputs.FAASR_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.TARGET_NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.TARGET_NAME }}:latest
